# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#        mvn com.google.cloud.tools:jib-maven-plugin:build -Djib.to.auth.username=${{ secrets.MY_USERNAME }} -Djib.to.auth.password=${{ secrets.MY_PASSWORD }} -Djib.container.jvmFlags=--add-opens,java.base/sun.nio.ch=ALL-UNNAMED -Djib.from.image=${{ secrets.JDK_IMAGE_11 }} -Dimage=${{ secrets.REGISTRY }}/operator-demo:v1.0.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      env:
        PASSWORD: ${{ secrets.MY_PASSWORD }}
      run: |
        docker login -u${{ secrets.MY_USERNAME }} -p${{ secrets.MY_PASSWORD }} registry.cn-shanghai.aliyuncs.com
        docker pull docker.elastic.co/kibana/kibana:7.6.2
        docker tag docker.elastic.co/kibana/kibana:7.6.2 registry.cn-shanghai.aliyuncs.com/qingmuio/kibana:7.6.2
        docker push registry.cn-shanghai.aliyuncs.com/qingmuio/kibana:7.6.2
